apiVersion: v1
kind: Pod
metadata:
  name: pvpod
  labels:
    name: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: nginxhtml
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: nginxhtml
    persistentVolumeClaim:
      claimName: nginx-pvc
  
      



    


